--- 
  #- name: Ajout de deb au dépots
  #  yum_repository: name=deb baseurl=http://packages.dotdeb.org description='dotdeb Installation' gpgkey=https://www.dotdeb.org/dotdeb.gpg
    #with_items:
      #- deb http://packages.dotdeb.org jessie all
      #- deb-src http://packages.dotdeb.org jessie all
      #- deb http://packages.dotdeb.org wheezy all
      #- deb-src http://packages.dotdeb.org wheezy all

 # - name: Ajout de deb-src au dépots
 #   yum_repository: name=deb-src baseurl=http://packages.dotdeb.org description='dotdeb Installation' gpgkey=https://www.dotdeb.org/dotdeb.gpg





  - name: Install epel from remote repo on CentOS 7
    yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present

  - name: Install remi from remote repo on CentOS 7
    yum: name=http://rpms.remirepo.net/enterprise/remi-release-7.rpm state=present

  # update yum
  - name: Yum update
    yum: name=* update_cache=yes
    
  # Install PHP7 packages.
  - name: Install PHP Packages
    yum: name={{ item }} enablerepo=ius state=present
    with_nested: "{{ yum_php_packages }}"
    when: yum_php_packages is defined
    notify: php restart


  - name: Installation de PHP
    yum: name={{item}} state=latest
    with_items: php_packages

 # - name: Retrait des functions dangereuse
 #   lineinfile: path=/etc/php/7.0/fpm/php.ini regexp='disable_functions[\s]?=' line='disable_functions=exec,passthru,shell_exec,proc_open,popen'
 #   lineinfile: path=/etc/php/7.0/fpm/php.ini regexp='post_max_size[\s]?=' line='post_max_size={{post_max_size}}'
 #   lineinfile: path=/etc/php/7.0/fpm/php.ini regexp='php_memory_limit[\s]?=' line='php_memory_limit={{php_memory_limit}}'
 #   lineinfile: path=/etc/php/7.0/fpm/php.ini regexp='php_upload_max_filesize[\s]?=' line='php_upload_max_filesize={{php_upload_max_filesize}}'
 #   lineinfile: path=/etc/php/7.0/fpm/php.ini regexp='php_timezone[\s]?=' line='php_timezone={{php_timezone}}'
 #   notify: php restart