---
- name: Installation des serveurs web
  hosts: web
  remote_user: root

  tasks:
  - name: Installation des items
    yum: name={{ item }} update_cache=yes state=latest
    with_items: 
      - vim
      - git
  - name: Création d'un utilisateur
    user: 
      name: jian
      comment: "Jian MA"
  - name: Ajout de la clef ssh
    authorized_key: 
      user: jian
      state: present
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
...