---
- name: Installation des serveurs web
  hosts: web
  remote_user: root
  vars:
    user: jian

  tasks:
  - name: Installation des items
    yum: name={{ item }} update_cache=yes state=latest
    with_items: 
      - vim
      - git

  - name: Création d'un utilisateur
    when: user is defined
    user: name={{ user }} comment="Jian MA"

  - name: Ajout de la clef ssh
    when: user is defined
    authorized_key: user={{ user }} state=present key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

  - name: Ajout user dans sudoers
    when: user is defined
    template: src=templates/sudoers.j2 dest=/etc/sudoers.d/{{user}}-sudoer validate='visudo -cf %s'
...