---
- name: Installation des serveurs web
  hosts: web
  remote_user: root

  tasks:
  - name: Installation des items
    yum: name={{ item }} update_cache=yes state=latest
    with_items: 
      - vim
      - git
      - epel-release
      - htop
...