---
  - name: Installation des items
    yum: name={{ item }} update_cache=yes state=latest
    with_items: 
      - vim
      - git
      - net-tools

  - name: Installation de java
    package: name={{ item }} state=installed
    with_items: "{{ java_packages }}"

  - name: Installation de spark
    include: spark.yml