---
  - name: Download Spark distribution
    get_url: url="{{ spark_mirror }}/spark-{{ spark_version }}.tgz" dest="{{ spark_src_dir }}/spark-{{ spark_version }}.tgz"

  - name: Extract Spark distribution
    unarchive: src="{{ spark_src_dir }}/spark-{{ spark_version }}.tgz" dest="{{ spark_src_dir }}"  creates="{{ spark_src_dir }}/spark-{{ spark_version }}" copy=no

  - name: Delete Spark tar
    file: path="{{ spark_src_dir }}/spark-{{ spark_version }}.tgz" state=absent

  - name: Start Spark
    command: "./start-slave.sh {{spark_master}}"
    args:
      chdir: "{{ spark_src_dir }}/spark-{{ spark_version }}/sbin"